import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.MvPolynomial.Symmetric.Defs
import Mathlib.Combinatorics.Enumerative.Partition.Basic
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.Quotient.Defs
import SymmetricPoly.Partition


/-! # The Fusion Ring

Formalizes the fusion ring Λ^{(N,L)} = Λ^{(N)} / I^{(N,L)} from the paper
"A concise proof of cylindric Schur positivity" and states the three
Goodman-Wenzl properties (with proofs deferred).
-/

noncomputable section





/-! ## Schur polynomials (axiomatic)
Schur polynomials are not in Mathlib...-/
def ssymm (μ : Partition) : MvPolynomial σ R := sorry

open MvPolynomial Module

namespace FusionRing

variable (σ R : Type*) [CommRing R] [Fintype σ] [DecidableEq σ]


/-! ## The fusion ideal and ring -/

/-- The generators of the fusion ideal: Schur polynomials s_μ where μ has at
    most N parts and its first part exceeds its N-th part by exactly L+1. -/
def fusionIdealGens (N L : ℕ) : Set (MvPolynomial σ R) :=
  {s | ∃ μ : Partition,
    μ.length ≤ N ∧
    μ.get 0 = μ.get (N - 1) + (L + 1) ∧
    s = ssymm σ R μ}

/-- The fusion ideal I^{(N,L)} ⊆ SymPoly N, generated by Schur polynomials
    s_λ satisfying λ₁ - λ_N = L+1. -/
def fusionIdeal (N L : ℕ) : Ideal (MvPolynomial σ R) :=
  Ideal.span (fusionIdealGens σ R N L)

/-- The fusion ring Λ^{(N,L)} = MvPolynomial σ R / fusionIdeal N L. -/
abbrev FusionRing (N L : ℕ) : Type _ := (MvPolynomial σ R) ⧸ (fusionIdeal σ R N L)

/-! ## Canonical elements -/

/-- The image of the Schur polynomial s_μ in the fusion ring. -/
def S (N L : ℕ) (μ : Partition) : FusionRing σ R N L :=
  Ideal.Quotient.mk (fusionIdeal σ R N L) (ssymm σ R μ)


/-- The image of the k-th complete homogeneous symmetric polynomial in the
    fusion ring. -/
def H (N L k : ℕ) : FusionRing σ R N L :=
  Ideal.Quotient.mk (fusionIdeal σ R N L) (hsymm σ R k)

/-! ## Horizontal strips -/

/-- The skew shape ν/μ is a horizontal strip: μ ≤ ν and the interlacing
    condition ν_{i+1} ≤ μ_i holds for all i (equivalently, each column of
    the skew shape contains at most one cell). -/
def IsHorizontalStrip (μ ν : Partition) : Prop :=
  μ ≤ ν ∧ ∀ i : ℕ, ν.rowLen (i + 1) ≤ μ.rowLen i

/-- The skew shape ρ/η is an (N,L)-horizontal strip of size k. -/
def IsNLHorizontalStrip (N L k : ℕ) (η ρ : Partition) : Prop :=
  IsNLPartition N L ρ ∧ IsHorizontalStrip η ρ ∧ ρ.size = η.size + k

/-! ## The Schur basis and Goodman-Wenzl properties -/

/-- The Schur basis of the fusion ring, indexed by (N,L)-partitions.
    Proof of existence due to Goodman-Wenzl; deferred. -/
def fusionSchurBasis (N L : ℕ) : Basis (NLPartition N L) ℤ (FusionRing N L) := by
  exact sorry

/-- Property (i): Each Schur basis vector equals the image of the corresponding
    Schur polynomial. Together with `fusionSchurBasis`, this shows that
    {S_λ : λ ∈ NLPartition N L} is a ℤ-basis for FusionRing N L. -/
theorem fusionSchurBasis_apply (N L : ℕ) (μ : NLPartition N L) :
    fusionSchurBasis N L μ = S N L μ.val := by sorry

/-- Property (ii): The fusion coefficients d^ρ_{μν} (structure constants of
    the Schur basis) are nonneg integers. -/
theorem fusionCoefficients_nonneg (N L : ℕ) (hN : 0 < N) (hL : 0 < L)
    (μ ν ρ : NLPartition N L) :
    0 ≤ (fusionSchurBasis N L).repr
          (fusionSchurBasis N L μ * fusionSchurBasis N L ν) ρ := by sorry

/-- Property (iii): The fusion Pieri rule. For any (N,L)-partition η and
    0 ≤ k ≤ L, the ρ-th coordinate of S_η · H_k in the Schur basis is 1 if
    ρ/η is an (N,L)-horizontal strip of size k, and 0 otherwise. -/
theorem fusionPieri (N L : ℕ) (hN : 0 < N) (hL : 0 < L)
    (η : NLPartition N L) (k : ℕ) (hk : k ≤ L) (ρ : NLPartition N L) :
    (fusionSchurBasis N L).repr (S N L η.val * H N L k) ρ =
    if IsNLHorizontalStrip N L k η.val ρ.val then 1 else 0 := by sorry


end LeanFusion

end
