import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.MvPolynomial.Symmetric.Defs
import Mathlib.Combinatorics.Enumerative.Partition.Basic
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Ideal.Quotient.Defs
import Mathlib.LinearAlgebra.Basis.Basic
import SymmetricPoly.Partition


/-! # The Fusion Ring

Starting to formalize the fusion ring defined in
``Littlewood-Richardson coefficients for Hecke algebras at roots of unity''
by Goodman and Wenzl. -/

noncomputable section


/-! ## The symmetric polynomial ring -/
/-- The ring of symmetric polynomials in N variables over ℤ. -/
abbrev SymPoly (N : PNat) : Type _ := ↥(MvPolynomial.symmetricSubalgebra (Fin N) ℤ)

/-! ## Schur polynomials
Schur polynomials are not in Mathlib...-/
def ssymm (N : PNat) (μ : Partition) : SymPoly N := sorry

open MvPolynomial Module Partition Classical

namespace FusionRing

/-! ## The fusion ideal and ring -/

/-- The generators of the fusion ideal: Schur polynomials s_μ where μ has at
    most N parts and its first part exceeds its N-th part by exactly L+1. -/
def fusionIdealGens (N L : PNat) : Set (SymPoly N) :=
  {s | ∃ μ : Partition,
    μ.length ≤ N ∧
    μ.part 0 = μ.part (N - 1) + (L + 1) ∧
    s = ssymm N μ}

/-- The fusion ideal is generated by Schur polynomials
    s_λ satisfying λ₁ - λ_N = L+1. -/
def fusionIdeal (N L : PNat) : Ideal (SymPoly N) :=
  Ideal.span (fusionIdealGens N L)

/-- The fusion ring Λ^{(N,L)} = quotient of symmetric polynomials by fusion ideal. -/
abbrev FusionRing (N L : PNat) : Type _ := (SymPoly N) ⧸ (fusionIdeal N L)

/-! ## Elements of the fusion ring -/

/-- The image of the Schur polynomial s_μ in the fusion ring. -/
def S (N L : PNat) (μ : Partition) : FusionRing N L :=
  Ideal.Quotient.mk (fusionIdeal N L) (ssymm N μ)


/-- The image of the k-th complete homogeneous symmetric polynomial in the
    fusion ring. -/
def H (N L : PNat) (k : ℕ) : FusionRing N L :=
  Ideal.Quotient.mk (fusionIdeal N L) ⟨MvPolynomial.hsymm (Fin N) ℤ k, by
    rw [MvPolynomial.mem_symmetricSubalgebra]
    exact MvPolynomial.hsymm_isSymmetric (Fin N) ℤ k⟩

/-! ## Goodman-Wenzl properties -/

/-- The Schur basis of the fusion ring, indexed by (N,L)-partitions.
    The basis vectors are the Schur images S_μ for μ ranging over NLPartitions.
    Proof of existence due to Goodman-Wenzl; deferred. -/
def fusionSchurBasis (N L : PNat) : Basis (NLPartition N L) ℤ (FusionRing N L) :=
  Basis.mk (v := fun μ : NLPartition N L => S N L μ)
    (by sorry) (by sorry)

/-- The fusion coefficients d^ρ_{μν} (structure constants of
    the Schur basis) are nonneg integers. -/
theorem fusionCoefficients_nonneg (μ ν ρ : NLPartition N L) :
    0 ≤ (fusionSchurBasis N L).repr
          (fusionSchurBasis N L μ * fusionSchurBasis N L ν) ρ := by sorry

/-- The fusion Pieri rule. For any (N,L)-partition η and
    0 ≤ k ≤ L, the ρ-th coordinate of S_η · H_k in the Schur basis is 1 if
    ρ/η is an (N,L)-horizontal strip of size k, and 0 otherwise. -/
theorem fusionPieri (N L : PNat)
    (η : NLPartition N L) (k : ℕ) (hk : k ≤ L) (ρ : NLPartition N L) :
    (fusionSchurBasis N L).repr (S N L η * H N L k) ρ =
    if (η ≺ ρ ∧ |ρ| = |η| + k ∧ ρ.getFirst ≤ η.getLast + L) then 1 else 0 := by sorry


end FusionRing

end
